version: "3"

services:
    server:
        build:
            context: .
            dockerfile: server/Dockerfile
        restart: always
        volumes:
            - .:/go/src/DataImpactProject
        container_name: server
        ports:
        - 8081:8081
    mongodb:
        image: mongo:4.2
        container_name: mongodb
        environment:
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/dev/null
        ports:
            - 27017:27017
        restart: always
